spring.application.name=api

#DataSource Properties
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#HikariCP Properties

#pool size = (núcleos do CPU × 2) + quantidade de discos => 12*2 + 1
spring.datasource.hikari.maximum-pool-size=25

#4,5 minutos
spring.datasource.hikari.idle-timeout=270000

#JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

#Logging Properties
logging.level.root=INFO
logging.level.org.hibernate.sql=DEBUG
logging.level.tracklistd.api=DEBUG

spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}

#url Documentaão api
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/documentation.html

#Para o LocalDateTime retornar no formato padrão, não transformar a data em um array
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

# caminho da configuração do firebase
firebase.config.path=${FIREBASE_JSON_PATH}
