# Comportamento do Hibernate em populate
# Esse perfil foi feito caso vc queira popular seu banco pra testar alguma coisa. De resto,ele funciona igual os outros
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop